name: Run tests and upload coverage

# Allow runners to get read only access to this repository files(set explicitly now because github requires it)
permissions:
  contents: read

on:
  pull_request:
      branches:
        - main
        - develop
  workflow_dispatch:
    inputs:
      test-app:
        description: 'Test this app'
        default: 'true'
        required: false

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        
      - name: Debug environment
        run: |
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "Installed dependencies:"
          npm list --depth=0

      - name: Run tests
        run: npx cross-env NODE_ENV=test jest --coverage

